version: '3.9'
services:
  acropolis:
    build: 
      context: ./Acropolis
      dockerfile: ./Acropolis.Api/Dockerfile
    cap_add:
      - "SYS_ADMIN"
    ports:
      - "8000:8080"
    depends_on:
      - rabbitmq
    # user: "root:root"

    environment:
      - ConnectionStrings__Database=Data Source=data/Acropolis.db;cache=shared
      - Telegram__UserToken=${TELEGRAM_TOKEN}
      - Telegram__ChatId=${TELEGRAM_CHAT_ID}
      - RabbitMq__User=${RABBITMQ_DEFAULT_USER}
      - RabbitMq__Password=${RABBITMQ_DEFAULT_PASS}
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
    volumes:
      - "./local/acropolis/data:/app/data"
      - "./local/acropolis/browser:/app/browser"

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./deploy/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  rabbitmq:

# docker compose --env-file local.env up --build -d