version: '3.9'
services:
  acropolis:
    build: 
      context: ./Acropolis
      dockerfile: ./Acropolis.Api/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ConnectionStrings__MessengerDatabase=Data Source=data/Acropolis_Messenger.db;cache=shared
      - Telegram__UserToken=${TELEGRAM_TOKEN}
      - Telegram__ChatId=${TELEGRAM_CHAT_ID}
      - YoutubeSettings__YoutubeDownloaderEndpoint=http://youtubedownloader:8080/
      - ScrapeSettings__ScraperEndpoint=http://scraper:8080/
    volumes:
      - "./local/acropolis/data:/app/data"

  scraper:
    image: ghcr.io/chthy/scraper:0.1.0-8
    ports:
      - "8001:8080"
    cap_add:
      - "SYS_ADMIN"
    environment:
      - ConnectionStrings__database=Data Source=data/Scraper.db;cache=shared
    volumes:
      - "./local/scraper/downloads:/app/downloads"
      - "./local/scraper/data:/app/data"
  
  youtubedownloader: 
    image: ghcr.io/chthy/youtubedownloader:0.1.0-25
    ports:
      - "8002:80"
    environment:
      - ConnectionStrings__database=Data Source=data/YoutubeDownloader.db;cache=shared
      - TelegramSettings__Enabled=false      
    volumes:
      - "./local/youtubedownloader/downloads:/app/downloads"
      - "./local/youtubedownloader/data:/app/data"

# docker compose --env-file local.env up --build -d