/* tslint:disable */
/* eslint-disable */
/**
 * Acropolis.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StoredVideo } from './stored-video';

/**
 * 
 * @export
 * @interface DownloadVideoState
 */
export interface DownloadVideoState {
    /**
     * 
     * @type {number}
     * @memberof DownloadVideoState
     */
    'rowVersion'?: number;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'currentState'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'requestedTimestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'downloadedTimestamp'?: string | null;
    /**
     * 
     * @type {StoredVideo}
     * @memberof DownloadVideoState
     */
    'storedVideo'?: StoredVideo;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'errorMessage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'errorTimestamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DownloadVideoState
     */
    'correlationId'?: string;
}

