/* tslint:disable */
/* eslint-disable */
/**
 * Acropolis.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PageMetaData
 */
export interface PageMetaData {
    /**
     * 
     * @type {string}
     * @memberof PageMetaData
     */
    'pageTitle'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PageMetaData
     */
    'domain'?: string | null;
}

