/* tslint:disable */
/* eslint-disable */
/**
 * Acropolis.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScrapePageState
 */
export interface ScrapePageState {
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'correlationId'?: string;
    /**
     * 
     * @type {number}
     * @memberof ScrapePageState
     */
    'rowVersion'?: number;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'currentState'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'requestedTimestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'scrapedTimestamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'domain'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'storageLocation'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'errorMessage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScrapePageState
     */
    'errorTimestamp'?: string | null;
}

