/* tslint:disable */
/* eslint-disable */
/**
 * Acropolis.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageMetaData } from './page-meta-data';
// May contain unused imports in some cases
// @ts-ignore
import type { Resource } from './resource';

/**
 * 
 * @export
 * @interface ScrapedPage
 */
export interface ScrapedPage {
    /**
     * 
     * @type {string}
     * @memberof ScrapedPage
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScrapedPage
     */
    'url'?: string | null;
    /**
     * 
     * @type {PageMetaData}
     * @memberof ScrapedPage
     */
    'metaData'?: PageMetaData;
    /**
     * 
     * @type {Array<Resource>}
     * @memberof ScrapedPage
     */
    'resources'?: Array<Resource> | null;
}

