/* tslint:disable */
/* eslint-disable */
/**
 * Acropolis.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VideoMetaData } from './video-meta-data';

/**
 * 
 * @export
 * @interface StoredVideo
 */
export interface StoredVideo {
    /**
     * 
     * @type {VideoMetaData}
     * @memberof StoredVideo
     */
    'metaData': VideoMetaData;
    /**
     * 
     * @type {string}
     * @memberof StoredVideo
     */
    'storageLocation': string;
}

