/* tslint:disable */
/* eslint-disable */
/**
 * Acropolis.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VideoMetaData
 */
export interface VideoMetaData {
    /**
     * 
     * @type {string}
     * @memberof VideoMetaData
     */
    'videoId': string;
    /**
     * 
     * @type {string}
     * @memberof VideoMetaData
     */
    'videoTitle': string;
    /**
     * 
     * @type {string}
     * @memberof VideoMetaData
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof VideoMetaData
     */
    'videoUploadTimestamp': string;
}

