//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export interface IDownloadClient {
    /**
     * @return Accepted
     */
    download(body: DownloadVideoRequest): Promise<void>;
}

export class DownloadClient implements IDownloadClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @return Accepted
     */
    download(body: DownloadVideoRequest, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/download";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDownload(_response);
        });
    }

    protected processDownload(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 202) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface IMigrateClient {
    /**
     * @return OK
     */
    pages(): Promise<void>;
    /**
     * @return OK
     */
    skippedpages(): Promise<void>;
    /**
     * @return OK
     */
    scrapedpages(): Promise<void>;
    /**
     * @return OK
     */
    videos(): Promise<void>;
    /**
     * @return OK
     */
    skippedvideos(): Promise<void>;
    /**
     * @return OK
     */
    downloadedvideos(): Promise<void>;
}

export class MigrateClient implements IMigrateClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @return OK
     */
    pages( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/migrate/pages";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPages(_response);
        });
    }

    protected processPages(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    skippedpages( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/migrate/skippedpages";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processSkippedpages(_response);
        });
    }

    protected processSkippedpages(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    scrapedpages( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/migrate/scrapedpages";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processScrapedpages(_response);
        });
    }

    protected processScrapedpages(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    videos( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/migrate/videos";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processVideos(_response);
        });
    }

    protected processVideos(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    skippedvideos( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/migrate/skippedvideos";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processSkippedvideos(_response);
        });
    }

    protected processSkippedvideos(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    downloadedvideos( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/migrate/downloadedvideos";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDownloadedvideos(_response);
        });
    }

    protected processDownloadedvideos(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface IPagesClient {
    /**
     * @return OK
     */
    pages(): Promise<ScrapedPage[]>;
    /**
     * @return OK
     */
    requestedPages(): Promise<ScrapePageState[]>;
    /**
     * @return Accepted
     */
    retryFailedScrapes(): Promise<void>;
}

export class PagesClient implements IPagesClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @return OK
     */
    pages( cancelToken?: CancelToken): Promise<ScrapedPage[]> {
        let url_ = this.baseUrl + "/pages";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processPages(_response);
        });
    }

    protected processPages(response: AxiosResponse): Promise<ScrapedPage[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ScrapedPage.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<ScrapedPage[]>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ScrapedPage[]>(null as any);
    }

    /**
     * @return OK
     */
    requestedPages( cancelToken?: CancelToken): Promise<ScrapePageState[]> {
        let url_ = this.baseUrl + "/pages/requested";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRequestedPages(_response);
        });
    }

    protected processRequestedPages(response: AxiosResponse): Promise<ScrapePageState[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ScrapePageState.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<ScrapePageState[]>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ScrapePageState[]>(null as any);
    }

    /**
     * @return Accepted
     */
    retryFailedScrapes( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/pages/failed/retry";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRetryFailedScrapes(_response);
        });
    }

    protected processRetryFailedScrapes(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 202) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface IVideosClient {
    /**
     * @return OK
     */
    videos(): Promise<DownloadedVideo[]>;
    /**
     * @return OK
     */
    requestedVideos(): Promise<DownloadVideoState>;
    /**
     * @return Accepted
     */
    retryAllFailedVideos(): Promise<void>;
    /**
     * @return Accepted
     */
    retryFailedVideo(id: string): Promise<void>;
}

export class VideosClient implements IVideosClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @return OK
     */
    videos( cancelToken?: CancelToken): Promise<DownloadedVideo[]> {
        let url_ = this.baseUrl + "/videos";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processVideos(_response);
        });
    }

    protected processVideos(response: AxiosResponse): Promise<DownloadedVideo[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(DownloadedVideo.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<DownloadedVideo[]>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<DownloadedVideo[]>(null as any);
    }

    /**
     * @return OK
     */
    requestedVideos( cancelToken?: CancelToken): Promise<DownloadVideoState> {
        let url_ = this.baseUrl + "/videos/requested";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRequestedVideos(_response);
        });
    }

    protected processRequestedVideos(response: AxiosResponse): Promise<DownloadVideoState> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = DownloadVideoState.fromJS(resultData200);
            return Promise.resolve<DownloadVideoState>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<DownloadVideoState>(null as any);
    }

    /**
     * @return Accepted
     */
    retryAllFailedVideos( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/videos/failed/retry";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRetryAllFailedVideos(_response);
        });
    }

    protected processRetryAllFailedVideos(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 202) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    retryFailedVideo(id: string, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/videos/failed/{id}/retry";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRetryFailedVideo(_response);
        });
    }

    protected processRetryFailedVideo(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 202) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status === 500) {
            const _responseText = response.data;
            let result500: any = null;
            let resultData500  = _responseText;
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export class DownloadVideoRequest implements IDownloadVideoRequest {
    url?: string | undefined;

    constructor(data?: IDownloadVideoRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): DownloadVideoRequest {
        data = typeof data === 'object' ? data : {};
        let result = new DownloadVideoRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["url"] = this.url;
        return data;
    }
}

export interface IDownloadVideoRequest {
    url?: string | undefined;
}

export class DownloadVideoState implements IDownloadVideoState {
    rowVersion?: number;
    currentState?: string | undefined;
    url?: string | undefined;
    requestedTimestamp?: string;
    downloadedTimestamp?: string | undefined;
    storedVideo?: StoredVideo;
    errorMessage?: string | undefined;
    errorTimestamp?: string | undefined;
    correlationId?: string;

    constructor(data?: IDownloadVideoState) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.rowVersion = _data["rowVersion"];
            this.currentState = _data["currentState"];
            this.url = _data["url"];
            this.requestedTimestamp = _data["requestedTimestamp"];
            this.downloadedTimestamp = _data["downloadedTimestamp"];
            this.storedVideo = _data["storedVideo"] ? StoredVideo.fromJS(_data["storedVideo"]) : <any>undefined;
            this.errorMessage = _data["errorMessage"];
            this.errorTimestamp = _data["errorTimestamp"];
            this.correlationId = _data["correlationId"];
        }
    }

    static fromJS(data: any): DownloadVideoState {
        data = typeof data === 'object' ? data : {};
        let result = new DownloadVideoState();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["rowVersion"] = this.rowVersion;
        data["currentState"] = this.currentState;
        data["url"] = this.url;
        data["requestedTimestamp"] = this.requestedTimestamp;
        data["downloadedTimestamp"] = this.downloadedTimestamp;
        data["storedVideo"] = this.storedVideo ? this.storedVideo.toJSON() : <any>undefined;
        data["errorMessage"] = this.errorMessage;
        data["errorTimestamp"] = this.errorTimestamp;
        data["correlationId"] = this.correlationId;
        return data;
    }
}

export interface IDownloadVideoState {
    rowVersion?: number;
    currentState?: string | undefined;
    url?: string | undefined;
    requestedTimestamp?: string;
    downloadedTimestamp?: string | undefined;
    storedVideo?: StoredVideo;
    errorMessage?: string | undefined;
    errorTimestamp?: string | undefined;
    correlationId?: string;
}

export class DownloadedVideo implements IDownloadedVideo {
    id?: string;
    url?: string | undefined;
    metaData?: VideoMetaData;
    readonly resources?: Resource[] | undefined;

    constructor(data?: IDownloadedVideo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.url = _data["url"];
            this.metaData = _data["metaData"] ? VideoMetaData.fromJS(_data["metaData"]) : <any>undefined;
            if (Array.isArray(_data["resources"])) {
                (<any>this).resources = [] as any;
                for (let item of _data["resources"])
                    (<any>this).resources!.push(Resource.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DownloadedVideo {
        data = typeof data === 'object' ? data : {};
        let result = new DownloadedVideo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["url"] = this.url;
        data["metaData"] = this.metaData ? this.metaData.toJSON() : <any>undefined;
        if (Array.isArray(this.resources)) {
            data["resources"] = [];
            for (let item of this.resources)
                data["resources"].push(item.toJSON());
        }
        return data;
    }
}

export interface IDownloadedVideo {
    id?: string;
    url?: string | undefined;
    metaData?: VideoMetaData;
    resources?: Resource[] | undefined;
}

export class PageMetaData implements IPageMetaData {
    pageTitle?: string | undefined;
    domain?: string | undefined;

    constructor(data?: IPageMetaData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pageTitle = _data["pageTitle"];
            this.domain = _data["domain"];
        }
    }

    static fromJS(data: any): PageMetaData {
        data = typeof data === 'object' ? data : {};
        let result = new PageMetaData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pageTitle"] = this.pageTitle;
        data["domain"] = this.domain;
        return data;
    }
}

export interface IPageMetaData {
    pageTitle?: string | undefined;
    domain?: string | undefined;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class Resource implements IResource {
    id?: string;
    storageLocation?: string | undefined;
    createdTimestamp?: string;
    readonly views?: number;

    constructor(data?: IResource) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.storageLocation = _data["storageLocation"];
            this.createdTimestamp = _data["createdTimestamp"];
            (<any>this).views = _data["views"];
        }
    }

    static fromJS(data: any): Resource {
        data = typeof data === 'object' ? data : {};
        let result = new Resource();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["storageLocation"] = this.storageLocation;
        data["createdTimestamp"] = this.createdTimestamp;
        data["views"] = this.views;
        return data;
    }
}

export interface IResource {
    id?: string;
    storageLocation?: string | undefined;
    createdTimestamp?: string;
    views?: number;
}

export class ScrapePageState implements IScrapePageState {
    correlationId?: string;
    rowVersion?: number;
    currentState?: string | undefined;
    url?: string | undefined;
    requestedTimestamp?: string;
    scrapedTimestamp?: string | undefined;
    domain?: string | undefined;
    title?: string | undefined;
    storageLocation?: string | undefined;
    errorMessage?: string | undefined;
    errorTimestamp?: string | undefined;

    constructor(data?: IScrapePageState) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.correlationId = _data["correlationId"];
            this.rowVersion = _data["rowVersion"];
            this.currentState = _data["currentState"];
            this.url = _data["url"];
            this.requestedTimestamp = _data["requestedTimestamp"];
            this.scrapedTimestamp = _data["scrapedTimestamp"];
            this.domain = _data["domain"];
            this.title = _data["title"];
            this.storageLocation = _data["storageLocation"];
            this.errorMessage = _data["errorMessage"];
            this.errorTimestamp = _data["errorTimestamp"];
        }
    }

    static fromJS(data: any): ScrapePageState {
        data = typeof data === 'object' ? data : {};
        let result = new ScrapePageState();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["correlationId"] = this.correlationId;
        data["rowVersion"] = this.rowVersion;
        data["currentState"] = this.currentState;
        data["url"] = this.url;
        data["requestedTimestamp"] = this.requestedTimestamp;
        data["scrapedTimestamp"] = this.scrapedTimestamp;
        data["domain"] = this.domain;
        data["title"] = this.title;
        data["storageLocation"] = this.storageLocation;
        data["errorMessage"] = this.errorMessage;
        data["errorTimestamp"] = this.errorTimestamp;
        return data;
    }
}

export interface IScrapePageState {
    correlationId?: string;
    rowVersion?: number;
    currentState?: string | undefined;
    url?: string | undefined;
    requestedTimestamp?: string;
    scrapedTimestamp?: string | undefined;
    domain?: string | undefined;
    title?: string | undefined;
    storageLocation?: string | undefined;
    errorMessage?: string | undefined;
    errorTimestamp?: string | undefined;
}

export class ScrapedPage implements IScrapedPage {
    id?: string;
    url?: string | undefined;
    metaData?: PageMetaData;
    readonly resources?: Resource[] | undefined;

    constructor(data?: IScrapedPage) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.url = _data["url"];
            this.metaData = _data["metaData"] ? PageMetaData.fromJS(_data["metaData"]) : <any>undefined;
            if (Array.isArray(_data["resources"])) {
                (<any>this).resources = [] as any;
                for (let item of _data["resources"])
                    (<any>this).resources!.push(Resource.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ScrapedPage {
        data = typeof data === 'object' ? data : {};
        let result = new ScrapedPage();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["url"] = this.url;
        data["metaData"] = this.metaData ? this.metaData.toJSON() : <any>undefined;
        if (Array.isArray(this.resources)) {
            data["resources"] = [];
            for (let item of this.resources)
                data["resources"].push(item.toJSON());
        }
        return data;
    }
}

export interface IScrapedPage {
    id?: string;
    url?: string | undefined;
    metaData?: PageMetaData;
    resources?: Resource[] | undefined;
}

export class StoredVideo implements IStoredVideo {
    metaData?: VideoMetaData;
    storageLocation?: string | undefined;

    constructor(data?: IStoredVideo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.metaData = _data["metaData"] ? VideoMetaData.fromJS(_data["metaData"]) : <any>undefined;
            this.storageLocation = _data["storageLocation"];
        }
    }

    static fromJS(data: any): StoredVideo {
        data = typeof data === 'object' ? data : {};
        let result = new StoredVideo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["metaData"] = this.metaData ? this.metaData.toJSON() : <any>undefined;
        data["storageLocation"] = this.storageLocation;
        return data;
    }
}

export interface IStoredVideo {
    metaData?: VideoMetaData;
    storageLocation?: string | undefined;
}

export class VideoMetaData implements IVideoMetaData {
    videoId?: string | undefined;
    videoTitle?: string | undefined;
    author?: string | undefined;
    videoUploadTimestamp?: string;

    constructor(data?: IVideoMetaData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.videoId = _data["videoId"];
            this.videoTitle = _data["videoTitle"];
            this.author = _data["author"];
            this.videoUploadTimestamp = _data["videoUploadTimestamp"];
        }
    }

    static fromJS(data: any): VideoMetaData {
        data = typeof data === 'object' ? data : {};
        let result = new VideoMetaData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["videoId"] = this.videoId;
        data["videoTitle"] = this.videoTitle;
        data["author"] = this.author;
        data["videoUploadTimestamp"] = this.videoUploadTimestamp;
        return data;
    }
}

export interface IVideoMetaData {
    videoId?: string | undefined;
    videoTitle?: string | undefined;
    author?: string | undefined;
    videoUploadTimestamp?: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}